cp actrecom.sh ../AMD-Megatron-LM/ 
cp basetrain70b.sh ../AMD-Megatron-LM/ 
cp benchmarking_3.sh ../AMD-Megatron-LM/ 
cp callmulti.sh ../AMD-Megatron-LM/ 
cp calltrain.sh ../AMD-Megatron-LM/ 
cp CODEOWNERS ../AMD-Megatron-LM/ 
cp CONTRIBUTING.md ../AMD-Megatron-LM/ 
cp debug_gloo.py ../AMD-Megatron-LM/ 
cp Dockerfile.ci ../AMD-Megatron-LM/ 
cp env_check.sh ../AMD-Megatron-LM/ 
cp jet-tests.yml ../AMD-Megatron-LM/ 
cp jiang-mgt-lm.tgz ../AMD-Megatron-LM/ 
cp LICENSE ../AMD-Megatron-LM/ 
cp MANIFEST.in ../AMD-Megatron-LM/ 
cp mean_log_value.py ../AMD-Megatron-LM/ 
cp prepare_bookcorpus_megatron_dataset.py ../AMD-Megatron-LM/ 
cp pretrain_bert.py ../AMD-Megatron-LM/ 
cp pretrain_gpt_data.py ../AMD-Megatron-LM/ 
cp pretrain_gpt.py ../AMD-Megatron-LM/ 
cp pretrain_ict.py ../AMD-Megatron-LM/ 
cp pretrain_retro.py ../AMD-Megatron-LM/ 
cp pretrain_t5.py ../AMD-Megatron-LM/ 
cp pretrain_vision_classify.py ../AMD-Megatron-LM/ 
cp pretrain_vision_dino.py ../AMD-Megatron-LM/ 
cp pretrain_vision_inpaint.py ../AMD-Megatron-LM/ 
cp pyproject.toml ../AMD-Megatron-LM/ 
cp README.md ../AMD-Megatron-LM/ 
cp remove_r.py ../AMD-Megatron-LM/ 
cp report_theoretical_memory.py ../AMD-Megatron-LM/ 
cp scan_multinode.py ../AMD-Megatron-LM/ 
cp setup.py ../AMD-Megatron-LM/ 
cp test.sh ../AMD-Megatron-LM/ 
cp train_llama2_70b.sh ../AMD-Megatron-LM/ 
cp train_llama2_jiang.sh ../AMD-Megatron-LM/ 
cp train_llama2_old.sh ../AMD-Megatron-LM/ 
cp train_llama2_single.sh ../AMD-Megatron-LM/ 
cp train_llama2.sh ../AMD-Megatron-LM/ 
cp train.sh ../AMD-Megatron-LM/ 
cp tune_and_train_llama2_jiang.sh ../AMD-Megatron-LM/ 
cp tune_and_train_llama2_old.sh ../AMD-Megatron-LM/ 
cp tune_and_train_llama2_single.sh ../AMD-Megatron-LM/ 
cp tune_and_train_llama2.sh
