MBS=4
TUNE_FOLDER="experiment/rocblas_7B_mbs${MBS}_tp4_pp1_seq4096"
TUNE_FILES="${TUNE_FOLDER}/full_tuned%d.csv"
ls $TUNE_FOLDER

HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 TORCH_BLAS_PREFER_HIPBLASLT=0 PYTORCH_TUNABLEOP_FILENAME=$TUNE_FILES PYTORCH_TUNABLEOP_TUNING=0 PYTORCH_TUNABLEOP_ENABLED=1 TP=4 PP=1 MBS=$MBS BS=128 EPOCHS=1 bash finetune_llama2_chat.sh
# HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 TORCH_BLAS_PREFER_HIPBLASLT=0 TP=4 PP=1 MBS=$MBS BS=128 EPOCHS=1 bash finetune_llama2_chat.sh --no-torch-compile
