FROM rocm/dev-ubuntu-22.04
WORKDIR /root
RUN apt update && apt install git vim wget -y
RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0
ADD . /root/ 
